server:
  port: 8080

spring:
  application:
    name: msa-invoices
  datasource:
    url: jdbc:postgresql://localhost:5433/invoices_db
    driver-class-name: org.postgresql.Driver
    username: invoices
    password: invoices


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  h2:
    console:
      enabled: false
