version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: invoice@123
      POSTGRES_DB: invoi
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./install.sql:/docker-entrypoint-initdb.d/install.sql
      - ./ddl:/docker-entrypoint-initdb.d/ddl

networks:
  default:
    driver: bridge

volumes:
  db_data: