version: '3.8'

services:
  db:
    container_name: postgres_db
    environment:
      POSTGRES_USER: invoices
      POSTGRES_PASSWORD: invoices
      POSTGRES_DB: invoices_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: